package com.containerwerk.configurator.model;

public enum ZubehoerVarianten {
    SOLAR_40,
    SOLAR_20,
    SOLAR_10,
    BALKON,
    DACHBEGRUENUNG_40,
    DACHBEGRUENUNG_20,
    DACHBEGRUENUNG_10,
    TERASSE_40,
    TERASSE_20,
    TERASSE_10,
    TECHNIKZENTRALE_HEIZUNG_10,
    TECHNIKZENTRALE_HEIZUNG_20,
    TECHNIKZENTRALE_HEIZUNG_30,
    DEZENTRALE_HEIZUNG,
    FASSADENMODUL
}
